package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1



/**
 * ArticuloProveedorId generated by hbm2java
 */
public class ArticuloProveedorId  implements java.io.Serializable {


     private int idArticulo;
     private int idProveedor;

    public ArticuloProveedorId() {
    }

    public ArticuloProveedorId(int idArticulo, int idProveedor) {
       this.idArticulo = idArticulo;
       this.idProveedor = idProveedor;
    }
   
    public int getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(int idArticulo) {
        this.idArticulo = idArticulo;
    }
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArticuloProveedorId) ) return false;
		 ArticuloProveedorId castOther = ( ArticuloProveedorId ) other; 
         
		 return (this.getIdArticulo()==castOther.getIdArticulo())
 && (this.getIdProveedor()==castOther.getIdProveedor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdArticulo();
         result = 37 * result + this.getIdProveedor();
         return result;
   }   


}


