package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ArticuloProveedor generated by hbm2java
 */
public class ArticuloProveedor  implements java.io.Serializable {


     private ArticuloProveedorId id;
     private Articulo articulo;
     private Proveedor proveedor;
     private BigDecimal precioCompra;
     private String referenciaProveedor;
     private Integer diasEntrega;
     private Boolean activo;

    public ArticuloProveedor() {
    }

	
    public ArticuloProveedor(ArticuloProveedorId id, Articulo articulo, Proveedor proveedor) {
        this.id = id;
        this.articulo = articulo;
        this.proveedor = proveedor;
    }
    public ArticuloProveedor(ArticuloProveedorId id, Articulo articulo, Proveedor proveedor, BigDecimal precioCompra, String referenciaProveedor, Integer diasEntrega, Boolean activo) {
       this.id = id;
       this.articulo = articulo;
       this.proveedor = proveedor;
       this.precioCompra = precioCompra;
       this.referenciaProveedor = referenciaProveedor;
       this.diasEntrega = diasEntrega;
       this.activo = activo;
    }
   
    public ArticuloProveedorId getId() {
        return this.id;
    }
    
    public void setId(ArticuloProveedorId id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public BigDecimal getPrecioCompra() {
        return this.precioCompra;
    }
    
    public void setPrecioCompra(BigDecimal precioCompra) {
        this.precioCompra = precioCompra;
    }
    public String getReferenciaProveedor() {
        return this.referenciaProveedor;
    }
    
    public void setReferenciaProveedor(String referenciaProveedor) {
        this.referenciaProveedor = referenciaProveedor;
    }
    public Integer getDiasEntrega() {
        return this.diasEntrega;
    }
    
    public void setDiasEntrega(Integer diasEntrega) {
        this.diasEntrega = diasEntrega;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }




}


