package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String dniCliente;
     private String nombreCl;
     private String apellidoCl;
     private String emailCl;
     private String telefonoCl;
     private String direccionCl;
     private String ciudad;
     private String provincia;
     private String codigoPostal;
     private Date fechaAlta;
     private String tipoCliente;
     private String notas;
     private String estado;
     private Date createdAt;
     private Date updatedAt;
     private Set ventas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String dniCliente, String nombreCl, String apellidoCl, String emailCl, String telefonoCl, String direccionCl, String ciudad, String provincia, String codigoPostal, Date fechaAlta, String tipoCliente, String notas, String estado, Date createdAt) {
        this.dniCliente = dniCliente;
        this.nombreCl = nombreCl;
        this.apellidoCl = apellidoCl;
        this.emailCl = emailCl;
        this.telefonoCl = telefonoCl;
        this.direccionCl = direccionCl;
        this.ciudad = ciudad;
        this.provincia = provincia;
        this.codigoPostal = codigoPostal;
        this.fechaAlta = fechaAlta;
        this.tipoCliente = tipoCliente;
        this.notas = notas;
        this.estado = estado;
        this.createdAt = createdAt;
    }
    
    
	
    public Cliente(String dniCliente, String nombreCl, Date fechaAlta, Date createdAt) {
        this.dniCliente = dniCliente;
        this.nombreCl = nombreCl;
        this.fechaAlta = fechaAlta;
        this.createdAt = createdAt;
    }
    public Cliente(String dniCliente, String nombreCl, String apellidoCl, String emailCl, String telefonoCl, String direccionCl, String ciudad, String provincia, String codigoPostal, Date fechaAlta, String tipoCliente, String notas, String estado, Date createdAt, Date updatedAt, Set ventas) {
       this.dniCliente = dniCliente;
       this.nombreCl = nombreCl;
       this.apellidoCl = apellidoCl;
       this.emailCl = emailCl;
       this.telefonoCl = telefonoCl;
       this.direccionCl = direccionCl;
       this.ciudad = ciudad;
       this.provincia = provincia;
       this.codigoPostal = codigoPostal;
       this.fechaAlta = fechaAlta;
       this.tipoCliente = tipoCliente;
       this.notas = notas;
       this.estado = estado;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.ventas = ventas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getDniCliente() {
        return this.dniCliente;
    }
    
    public void setDniCliente(String dniCliente) {
        this.dniCliente = dniCliente;
    }
    public String getNombreCl() {
        return this.nombreCl;
    }
    
    public void setNombreCl(String nombreCl) {
        this.nombreCl = nombreCl;
    }
    public String getApellidoCl() {
        return this.apellidoCl;
    }
    
    public void setApellidoCl(String apellidoCl) {
        this.apellidoCl = apellidoCl;
    }
    public String getEmailCl() {
        return this.emailCl;
    }
    
    public void setEmailCl(String emailCl) {
        this.emailCl = emailCl;
    }
    public String getTelefonoCl() {
        return this.telefonoCl;
    }
    
    public void setTelefonoCl(String telefonoCl) {
        this.telefonoCl = telefonoCl;
    }
    public String getDireccionCl() {
        return this.direccionCl;
    }
    
    public void setDireccionCl(String direccionCl) {
        this.direccionCl = direccionCl;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getTipoCliente() {
        return this.tipoCliente;
    }
    
    public void setTipoCliente(String tipoCliente) {
        this.tipoCliente = tipoCliente;
    }
    public String getNotas() {
        return this.notas;
    }
    
    public void setNotas(String notas) {
        this.notas = notas;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


