package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Comprapedido generated by hbm2java
 */
public class Comprapedido  implements java.io.Serializable {


     private Integer idPedido;
     private Proveedor proveedor;
     private Date fechaPedido;
     private String estado;
     private BigDecimal total;
     private Set lineacompras = new HashSet(0);

    public Comprapedido() {
    }

	
    public Comprapedido(Proveedor proveedor, Date fechaPedido) {
        this.proveedor = proveedor;
        this.fechaPedido = fechaPedido;
    }
    public Comprapedido(Proveedor proveedor, Date fechaPedido, String estado, BigDecimal total, Set lineacompras) {
       this.proveedor = proveedor;
       this.fechaPedido = fechaPedido;
       this.estado = estado;
       this.total = total;
       this.lineacompras = lineacompras;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFechaPedido() {
        return this.fechaPedido;
    }
    
    public void setFechaPedido(Date fechaPedido) {
        this.fechaPedido = fechaPedido;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public Set getLineacompras() {
        return this.lineacompras;
    }
    
    public void setLineacompras(Set lineacompras) {
        this.lineacompras = lineacompras;
    }




}


