package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1



/**
 * Garantia generated by hbm2java
 */
public class Garantia  implements java.io.Serializable {


     private Integer idGarantia;
     private Inventario inventario;
     private String tipoGarantia;

    public Garantia() {
    }

	
    public Garantia(Inventario inventario) {
        this.inventario = inventario;
    }
    public Garantia(Inventario inventario, String tipoGarantia) {
       this.inventario = inventario;
       this.tipoGarantia = tipoGarantia;
    }
   
    public Integer getIdGarantia() {
        return this.idGarantia;
    }
    
    public void setIdGarantia(Integer idGarantia) {
        this.idGarantia = idGarantia;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public String getTipoGarantia() {
        return this.tipoGarantia;
    }
    
    public void setTipoGarantia(String tipoGarantia) {
        this.tipoGarantia = tipoGarantia;
    }




}


