package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1


import java.time.Instant;
import java.util.HashSet;
import java.util.Set;
import java.time.LocalDateTime;
import java.util.Date;
import org.hibernate.annotations.CreationTimestamp;


/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private String numeroSerie;
     private Articulo articulo;
     private Ubicacion ubicacion;     
     private Estado_inventario estado;
     @CreationTimestamp
     private Date fechaEntrada;
     private Proveedor proveedor;
     private Set garantias = new HashSet(0);
     private Set lineaventas = new HashSet(0);

    public Inventario() {
    }
    
    public Inventario(String numeroSerie, Articulo articulo, Ubicacion ubicacion, Estado_inventario estado) {
        this.numeroSerie = numeroSerie;
        this.articulo = articulo;
        this.ubicacion = ubicacion;
        this.estado = estado;        
    }

	
    
    public Inventario(String numeroSerie, Articulo articulo, Ubicacion ubicacion, Estado_inventario estado, Set garantias, Set lineaventas) {
        this.numeroSerie = numeroSerie;
        this.articulo = articulo;
        this.ubicacion = ubicacion;
        this.estado = estado;
        this.garantias = garantias;
        this.lineaventas = lineaventas;
    }

    public Inventario(String numeroSerie, Articulo articulo, Ubicacion ubicacion, Estado_inventario estado, Date fechaEntrada, Proveedor proveedor) {
        this.numeroSerie = numeroSerie;
        this.articulo = articulo;
        this.ubicacion = ubicacion;
        this.estado = estado;
        this.fechaEntrada = fechaEntrada;
        this.proveedor = proveedor;
    }  
    
    
    public Inventario(String numeroSerie, Articulo articulo, Ubicacion ubicacion, Estado_inventario estado, Proveedor proveedor) {
        this.numeroSerie = numeroSerie;
        this.articulo = articulo;
        this.ubicacion = ubicacion;
        this.estado = estado;
        this.proveedor = proveedor;
    }
   
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Ubicacion getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Ubicacion ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Estado_inventario getEstado() {
        return estado;
    }

    public void setEstado(Estado_inventario estado) {
        this.estado = estado;
    }
    
    public Set getGarantias() {
        return this.garantias;
    }
    
    public void setGarantias(Set garantias) {
        this.garantias = garantias;
    }
    public Set getLineaventas() {
        return this.lineaventas;
    }
    
    public void setLineaventas(Set lineaventas) {
        this.lineaventas = lineaventas;
    }

    public Date getFechaEntrada() {
        return fechaEntrada;
    }

    public void setFechaEntrada(Date fechaEntrada) {
        this.fechaEntrada = fechaEntrada;
    }
    
    public Proveedor getProveedor() {
        return proveedor;
    }

    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    
    




}


