package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1



/**
 * Lineacompra generated by hbm2java
 */
public class Lineacompra  implements java.io.Serializable {


     private Integer idCompra;
     private Comprapedido comprapedido;
     private int cantidad;

    public Lineacompra() {
    }

    public Lineacompra(Comprapedido comprapedido, int cantidad) {
       this.comprapedido = comprapedido;
       this.cantidad = cantidad;
    }
   
    public Integer getIdCompra() {
        return this.idCompra;
    }
    
    public void setIdCompra(Integer idCompra) {
        this.idCompra = idCompra;
    }
    public Comprapedido getComprapedido() {
        return this.comprapedido;
    }
    
    public void setComprapedido(Comprapedido comprapedido) {
        this.comprapedido = comprapedido;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


