package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1



/**
 * Lineaventa generated by hbm2java
 */
public class Lineaventa  implements java.io.Serializable {


     private Integer idLineaVenta;
     private Inventario inventario;
     private Venta venta;

    public Lineaventa() {
    }

    public Lineaventa(Inventario inventario, Venta venta) {
       this.inventario = inventario;
       this.venta = venta;
    }
   
    public Integer getIdLineaVenta() {
        return this.idLineaVenta;
    }
    
    public void setIdLineaVenta(Integer idLineaVenta) {
        this.idLineaVenta = idLineaVenta;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }




}


