package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private String nombreProov;
     private String detalleAdicional;
     private String email;
     private String telefono;
     private String direccion;
     private Boolean activo;
     private Set articuloProveedors = new HashSet(0);
     private Set comprapedidos = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombreProov) {
        this.nombreProov = nombreProov;
    }
    public Proveedor(String nombreProov, String detalleAdicional, String email, String telefono, String direccion, Boolean activo, Set articuloProveedors, Set comprapedidos) {
       this.nombreProov = nombreProov;
       this.detalleAdicional = detalleAdicional;
       this.email = email;
       this.telefono = telefono;
       this.direccion = direccion;
       this.activo = activo;
       this.articuloProveedors = articuloProveedors;
       this.comprapedidos = comprapedidos;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public String getNombreProov() {
        return this.nombreProov;
    }
    
    public void setNombreProov(String nombreProov) {
        this.nombreProov = nombreProov;
    }
    public String getDetalleAdicional() {
        return this.detalleAdicional;
    }
    
    public void setDetalleAdicional(String detalleAdicional) {
        this.detalleAdicional = detalleAdicional;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set getArticuloProveedors() {
        return this.articuloProveedors;
    }
    
    public void setArticuloProveedors(Set articuloProveedors) {
        this.articuloProveedors = articuloProveedors;
    }
    public Set getComprapedidos() {
        return this.comprapedidos;
    }
    
    public void setComprapedidos(Set comprapedidos) {
        this.comprapedidos = comprapedidos;
    }

     @Override
    public String toString(){
        return nombreProov;
    }


}


