package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ubicacion generated by hbm2java
 */
public class Ubicacion  implements java.io.Serializable {


     private Integer idUbicacion;
     private int pasillo;
     private int estante;
     private Set inventarios = new HashSet(0);

    public Ubicacion() {
    }

	
    public Ubicacion(int pasillo, int estante) {
        this.pasillo = pasillo;
        this.estante = estante;
    }
    public Ubicacion(int pasillo, int estante, Set inventarios) {
       this.pasillo = pasillo;
       this.estante = estante;
       this.inventarios = inventarios;
    }
   
    public Integer getIdUbicacion() {
        return this.idUbicacion;
    }
    
    public void setIdUbicacion(Integer idUbicacion) {
        this.idUbicacion = idUbicacion;
    }
    public int getPasillo() {
        return this.pasillo;
    }
    
    public void setPasillo(int pasillo) {
        this.pasillo = pasillo;
    }
    public int getEstante() {
        return this.estante;
    }
    
    public void setEstante(int estante) {
        this.estante = estante;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }




}


