package pojos_package;
// Generated 25-abr-2026 14:27:24 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private Cliente cliente;
     private Date fechaVenta;
     private BigDecimal total;
     private String estado;
     private String metodoPago;
     private String pedidoExterno;
     private Set lineaventas = new HashSet(0);

    public Venta() {
    }
	
    public Venta(Cliente cliente, Date fechaVenta) {
        this.cliente = cliente;
        this.fechaVenta = fechaVenta;
    }
    public Venta(Cliente cliente, Date fechaVenta, BigDecimal total, String estado, String metodoPago, Set lineaventas) {
       this.cliente = cliente;
       this.fechaVenta = fechaVenta;
       this.total = total;
       this.estado = estado;
       this.metodoPago = metodoPago;
       this.lineaventas = lineaventas;
    }
    
    public Venta(Cliente cliente, Date fechaVenta, BigDecimal total, String estado, String metodoPago, String pedidoExterno) {
        this.cliente = cliente;
        this.fechaVenta = fechaVenta;
        this.total = total;
        this.estado = estado;
        this.metodoPago = metodoPago;
        this.pedidoExterno = pedidoExterno;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }
    public Set getLineaventas() {
        return this.lineaventas;
    }
    
    public void setLineaventas(Set lineaventas) {
        this.lineaventas = lineaventas;
    }
    
    public String getPedidoExterno() {
        return this.pedidoExterno;
    }

    public void setPedidoExterno(String pedidoExterno) {
        this.pedidoExterno = pedidoExterno;
    }


}


