/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.Color;
import vista.componentes.graficas.CurveLineChart;
import vista.componentes.graficas.ModelChart;

/**
 *
 * @author Usuario
 */
public class VentanaGraficas extends javax.swing.JPanel {
    private CurveLineChart chartAnimado;
    /**
     * Creates new form VentanaGraficas
     */
    public VentanaGraficas() {
        initComponents();
        inicializar_y_estilizar_grafica();
        cargar_datos_simulados();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Graficas");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/analytics_50dp_000000_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N

        panelContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(847, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
    
    private void inicializar_y_estilizar_grafica() {    
    chartAnimado = new CurveLineChart();    
    chartAnimado.setBackground(new Color(24, 24, 27));
    
    
    chartAnimado.setTitle("Ocupación de Stock por Pasillos");
    chartAnimado.addLegend("Capacidad Actual", new Color(12, 194, 240));
    chartAnimado.addLegend("Límite de Alerta", new Color(238, 7, 137));
    
    
    panelContenedor.setLayout(new java.awt.BorderLayout());
    panelContenedor.add(chartAnimado, java.awt.BorderLayout.CENTER);
    panelContenedor.validate();
    }
    
    private void cargar_datos_simulados() {
        chartAnimado.clear();
        
        
        chartAnimado.addData(new ModelChart("Pasillo A", new double[]{45, 80}));
        chartAnimado.addData(new ModelChart("Pasillo B", new double[]{75, 80}));
        chartAnimado.addData(new ModelChart("Pasillo C", new double[]{20, 80}));
        chartAnimado.addData(new ModelChart("Pasillo D", new double[]{95, 80})); 
        chartAnimado.addData(new ModelChart("Pasillo E", new double[]{60, 80}));
        
        
        chartAnimado.start();
    }

}
