/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Usuario
 */
public class VentanaLogin extends javax.swing.JPanel {

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnAceptarLogin = new javax.swing.JButton();
        btnCancelarLogin = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 247, 96, 44));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 326, 96, 44));

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUsuario.setText("jTextField1");
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 256, 231, 27));

        txtPassword.setText("jPasswordField1");
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 339, 231, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setText("LOGIN");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 78, 145, 74));

        btnAceptarLogin.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnAceptarLogin.setText("Aceptar");
        add(btnAceptarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 465, 117, 34));

        btnCancelarLogin.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnCancelarLogin.setText("Cancelar");
        add(btnCancelarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 465, 117, 34));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarLogin;
    private javax.swing.JButton btnCancelarLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
