/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.BBDD;
import pojos_package.Cliente;
import pojos_package.Provincia;

/**
 *
 * @author Usuario
 */
public class VentanaListaClientes extends javax.swing.JPanel {
    
    String[] estados = {"activo", "inactivo", "bloqueado"};
    
    /**
     * Creates new form VentanaListaClientes
     */
    public VentanaListaClientes() {
        initComponents();
        jTable1.setDefaultEditor(Object.class, null);
        agregar_listener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogRegCliente = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtTfno = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        cmbProvincia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPostal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaNotas = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        btnRegCliente = new javax.swing.JButton();
        checkBoxDni = new javax.swing.JCheckBox();
        dialogDetallesCliente = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        txtDetallesNombre = new javax.swing.JTextField();
        txtDetallesApellidos = new javax.swing.JTextField();
        txtDetallesEmilio = new javax.swing.JTextField();
        txtDetallesTfno = new javax.swing.JTextField();
        txtDetallesDireccion = new javax.swing.JTextField();
        txtDetallesCiudad = new javax.swing.JTextField();
        txtDetallesCodPostal = new javax.swing.JTextField();
        txtDetallesAlta = new javax.swing.JTextField();
        txtDetallesDNI = new javax.swing.JTextField();
        txtDetallesTipoCliente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDetalles = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        checkBoxDetalles = new javax.swing.JCheckBox();
        cmbDetallesProvincia = new javax.swing.JComboBox<>();
        cmbDetallesEstado = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        efeCinco = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        dialogRegCliente.setBackground(new java.awt.Color(255, 51, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Nuevo cliente");

        txtDNI.setText("jTextField1");

        txtNombre.setText("jTextField1");

        txtApellido.setText("jTextField1");

        txtMail.setText("jTextField1");

        txtTfno.setText("jTextField1");

        txtDireccion.setText("jTextField1");

        txtCiudad.setText("jTextField1");

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("DNI");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Apellido(s)");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("e-mail");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Telefono");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Direccion");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Ciudad");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Provincia");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("C.P.");

        txtPostal.setText("jTextField1");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Tipo de cliente");

        cmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Estado");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEstado.setPreferredSize(new java.awt.Dimension(54, 24));

        txtAreaNotas.setColumns(20);
        txtAreaNotas.setRows(5);
        jScrollPane2.setViewportView(txtAreaNotas);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Notas");

        btnRegCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnRegCliente.setText("Registrar");
        btnRegCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogRegClienteLayout = new javax.swing.GroupLayout(dialogRegCliente.getContentPane());
        dialogRegCliente.getContentPane().setLayout(dialogRegClienteLayout);
        dialogRegClienteLayout.setHorizontalGroup(
            dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTfno, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(cmbProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxDni)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtPostal))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(btnRegCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogRegClienteLayout.setVerticalGroup(
            dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(checkBoxDni))
                .addGap(18, 18, 18)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(25, 25, 25)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jScrollPane2))
                .addGap(48, 48, 48)
                .addComponent(btnRegCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        dialogDetallesCliente.setBackground(new java.awt.Color(255, 102, 0));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Detalles");

        txtDetallesNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesNombre.setText("jTextField1");

        txtDetallesApellidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesApellidos.setText("jTextField1");

        txtDetallesEmilio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesEmilio.setText("jTextField1");

        txtDetallesTfno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesTfno.setText("jTextField1");

        txtDetallesDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesDireccion.setText("jTextField1");

        txtDetallesCiudad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesCiudad.setText("jTextField1");

        txtDetallesCodPostal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesCodPostal.setText("jTextField1");

        txtDetallesAlta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesAlta.setText("jTextField1");

        txtDetallesDNI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesDNI.setText("jTextField1");

        txtDetallesTipoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesTipoCliente.setText("jTextField1");

        txtAreaDetalles.setColumns(20);
        txtAreaDetalles.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAreaDetalles.setRows(5);
        jScrollPane3.setViewportView(txtAreaDetalles);

        btnActualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");

        checkBoxDetalles.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        checkBoxDetalles.setText("Editar");
        checkBoxDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDetallesActionPerformed(evt);
            }
        });

        cmbDetallesProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbDetallesEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout dialogDetallesClienteLayout = new javax.swing.GroupLayout(dialogDetallesCliente.getContentPane());
        dialogDetallesCliente.getContentPane().setLayout(dialogDetallesClienteLayout);
        dialogDetallesClienteLayout.setHorizontalGroup(
            dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(386, 386, 386)
                        .addComponent(checkBoxDetalles))
                    .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDetallesApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetallesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetallesEmilio, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetallesTfno, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetallesCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbDetallesProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDetallesDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbDetallesEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDetallesDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(txtDetallesCodPostal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(txtDetallesAlta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(txtDetallesTipoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        dialogDetallesClienteLayout.setVerticalGroup(
            dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(checkBoxDetalles)))
                .addGap(18, 18, 18)
                .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                        .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDetallesNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetallesDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDetallesApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetallesCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDetallesEmilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetallesAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDetallesTfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetallesTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDetallesCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDetallesDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18)
                .addGroup(dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                        .addComponent(cmbDetallesProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnActualizar))
                    .addComponent(cmbDetallesEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        setBackground(new java.awt.Color(255, 51, 0));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Lista de Clientes");

        efeCinco.setText("Refrescar");
        efeCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efeCincoActionPerformed(evt);
            }
        });

        btnNuevoCliente.setText("Nuevo cliente");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(efeCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(efeCinco))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevoCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    


// efeCinco: botón para refrescar la lista de clientes
    private void efeCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efeCincoActionPerformed
       cargarClientes();
    }//GEN-LAST:event_efeCincoActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        dialogRegCliente.setSize(815, 630);
        dialogRegCliente.setLocationRelativeTo(this);
        dialogRegCliente.setVisible(true);
        limpiar_campos_registro();
        cargar_estados();
        cargar_provincias();
        
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnRegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegClienteActionPerformed
        Cliente cl = new Cliente();
        
        //Validaciones (falta: estado, Provincia)
        if(!evaluar_dni(txtDNI.getText())){
            return;
        }
        if(!evaluar_mail(txtMail.getText().trim().toLowerCase())){
            return;
        }
        if(!validar_telefono(txtTfno.getText().trim())){
            return;
        }
        if(!validar_estado(cmbEstado.getSelectedItem().toString())){
            return;
        }
        if(!evaluar_campos_vacios()){
            return;
        }
        
        
        //Crear Objeto
        cl.setDniCliente(txtDNI.getText().trim().toUpperCase());
        cl.setNombreCl(txtNombre.getText().trim());
        cl.setApellidoCl(txtApellido.getText().trim());        
        cl.setEmailCl(txtMail.getText().trim().toLowerCase());               
        cl.setTelefonoCl(txtTfno.getText().trim());
        cl.setDireccionCl(txtDireccion.getText().trim());
        cl.setCiudad(txtCiudad.getText().trim());
        cl.setCodigoPostal(txtPostal.getText().trim());
        cl.setFechaAlta(new Date());
        cl.setCreatedAt(new Date());
        cl.setNotas(txtAreaNotas.getText());
        cl.setEstado(cmbEstado.getSelectedItem().toString());
        cl.setProvincia(cmbProvincia.getSelectedItem().toString());
        
        //Guardar objeto
        BBDD bd = new BBDD();
        boolean exito = bd.registrar_cliente(cl);
        evaluar_insercion(exito);
    }//GEN-LAST:event_btnRegClienteActionPerformed

    private void checkBoxDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDetallesActionPerformed
        permitir_edicion(checkBoxDetalles.isSelected());
    }//GEN-LAST:event_checkBoxDetallesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnRegCliente;
    private javax.swing.JCheckBox checkBoxDetalles;
    private javax.swing.JCheckBox checkBoxDni;
    private javax.swing.JComboBox<String> cmbDetallesEstado;
    private javax.swing.JComboBox<String> cmbDetallesProvincia;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JComboBox<String> cmbTipoCliente;
    private javax.swing.JDialog dialogDetallesCliente;
    private javax.swing.JDialog dialogRegCliente;
    private javax.swing.JButton efeCinco;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextArea txtAreaDetalles;
    private javax.swing.JTextArea txtAreaNotas;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDetallesAlta;
    private javax.swing.JTextField txtDetallesApellidos;
    private javax.swing.JTextField txtDetallesCiudad;
    private javax.swing.JTextField txtDetallesCodPostal;
    private javax.swing.JTextField txtDetallesDNI;
    private javax.swing.JTextField txtDetallesDireccion;
    private javax.swing.JTextField txtDetallesEmilio;
    private javax.swing.JTextField txtDetallesNombre;
    private javax.swing.JTextField txtDetallesTfno;
    private javax.swing.JTextField txtDetallesTipoCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPostal;
    private javax.swing.JTextField txtTfno;
    // End of variables declaration//GEN-END:variables

    public void cargarClientes() {
        BBDD bd = new BBDD();
        List<Cliente> lista_de_clientes = bd.listar_clientes();
        
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("e-Mail");
        modelo.addColumn("Alta");
        modelo.addColumn("Estado");
        
        if (lista_de_clientes != null) {
        for (Cliente c : lista_de_clientes) {
            Object[] fila = new Object[6];
            fila[0] = c.getDniCliente();
            fila[1] = c.getNombreCl();
            fila[2] = c.getApellidoCl();
            fila[3] = c.getEmailCl();
            Date alta = c.getFechaAlta();            
            fila[4] = transform(alta);
            fila[5] = c.getEstado();
            modelo.addRow(fila);
            }
        }
        jTable1.setModel(modelo);
    }

    private void agregar_listener() {
        jTable1.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int fila = jTable1.getSelectedRow();
                    if (fila != -1) {
                        String dni = jTable1.getValueAt(fila, 0).toString();
                        
                        BBDD bd = new BBDD();
                        Cliente c = bd.obtener_cliente_por_dni(dni);
                        
                        if(c != null){
                            txtDetallesDNI.setText(c.getDniCliente());
                            txtDetallesNombre.setText(c.getNombreCl());
                            txtDetallesApellidos.setText(c.getApellidoCl());
                            txtDetallesEmilio.setText(c.getEmailCl());
                            txtDetallesDireccion.setText(c.getDireccionCl());
                            txtDetallesTfno.setText(c.getTelefonoCl());
                            txtDetallesCodPostal.setText(c.getCodigoPostal());
                            txtDetallesTipoCliente.setText(c.getTipoCliente());
                            if(c.getFechaAlta() != null){
                                txtDetallesAlta.setText(transform(c.getFechaAlta()));
                            }
                            txtAreaDetalles.setText(c.getNotas());
                            
                            checkBoxDetalles.setSelected(false);
                            permitir_edicion(false);
                            
                            dialogDetallesCliente.pack();
                            dialogDetallesCliente.setSize(743, 510);
                            dialogDetallesCliente.setLocationRelativeTo(null);
                            dialogDetallesCliente.setVisible(true);
                            
                        }
                    }
                }
            }

        });
        
    }
    
    private void limpiar_campos_registro(){
        txtDNI.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCiudad.setText("");
        txtDireccion.setText("");
        txtMail.setText("");
        txtPostal.setText("");
        txtTfno.setText("");
    }
    
    private void cargar_estados(){
        cmbEstado.removeAllItems();
        for (String estado : estados)
        {
            cmbEstado.addItem(estado);
        }
    }

    private void evaluar_insercion(boolean exito) {
        if(!exito){
            JOptionPane.showMessageDialog(btnRegCliente, "No se pudo registrar el cliente\nVerifique correcta inserción de datos", "Aviso", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(btnRegCliente, "Cliente registrado", "Confirmación", JOptionPane.WARNING_MESSAGE);
        }
    }

    private boolean evaluar_dni(String este_dni) {
        Boolean correcto = false;
        String dni = este_dni.trim().toUpperCase();
        if(!dni.matches(".*[A-Z]$")){
            JOptionPane.showMessageDialog(this, "Introduzca DNI válido", "Aviso", JOptionPane.ERROR_MESSAGE);
            txtDNI.setText("");
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private boolean evaluar_mail(String emilio) {
        Boolean correcto = false;
        if(!emilio.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")){
            JOptionPane.showMessageDialog(this, "Introduzca email válido", "Aviso", JOptionPane.ERROR_MESSAGE);
            txtMail.setText("");
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private boolean validar_telefono(String tfno) {
        Boolean correcto = false;
        if(!tfno.matches("^[0-9]{9}$")){
            JOptionPane.showMessageDialog(this, "Introduzca telefono válido", "Aviso", JOptionPane.ERROR_MESSAGE);
            txtTfno.setText("");
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private void cargar_provincias() {
        cmbProvincia.removeAllItems();
        BBDD bd = new BBDD();
        List<Provincia> listado_provincias = bd.listar_provincias();
        for (Provincia listado : listado_provincias)
        {
            cmbProvincia.addItem(listado.getNombreProvincia());
        }
    }

    private boolean validar_estado(String estado) {
        Boolean correcto = false;        
        if(!estado.matches("activo")){
            JOptionPane.showConfirmDialog(this, "El cliente no está configurado activo", "Aviso", JOptionPane.OK_OPTION);
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private boolean evaluar_campos_vacios() {
        Boolean correcto = false;
        if(txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() || txtCiudad.getText().isEmpty() || txtDireccion.getText().isEmpty() || txtTfno.getText().isEmpty()){
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private String transform(Date alta) {
        if (alta == null) {
            return ""; 
        }       
        SimpleDateFormat formateador = new SimpleDateFormat("dd-MM-yyyy");       
        return formateador.format(alta);
    }
    
    private void permitir_edicion(boolean activar){
        txtDetallesDNI.setEditable(false);
        txtDetallesAlta.setEditable(false);
        
        txtDetallesNombre.setEditable(activar);
        txtDetallesApellidos.setEditable(activar);
        txtDetallesEmilio.setEditable(activar);
        txtDetallesDireccion.setEditable(activar);
        txtDetallesCodPostal.setEditable(activar);
        txtDetallesTfno.setEditable(activar);
        txtDetallesCiudad.setEditable(activar);        
        txtDetallesTipoCliente.setEditable(activar);
        cmbDetallesProvincia.setEditable(activar);
        cmbDetallesEstado.setEditable(activar);
        btnActualizar.setEnabled(activar);
    }    
}


//tareas

//cargar lista
//mostrar en tabla
//boton refrescar
//boton registro de cliente


