/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.BBDD;
import pojos_package.Cliente;
import pojos_package.Provincia;
import pojos_package.Venta;

/**
 *
 * @author Usuario
 */
public class VentanaListaClientes extends javax.swing.JPanel {
    
    String[] estados = {"activo", "inactivo", "bloqueado"};
    
    /**
     * Creates new form VentanaListaClientes
     */
    public VentanaListaClientes() {
        initComponents();
        tablaListaClientes.setDefaultEditor(Object.class, null);
        configurar_tabla_historial();
        configurar_tabla_inactivos();
        agregar_listener();
        asignar_estados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogRegCliente = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtTfno = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        cmbProvincia = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPostal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaNotas = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        btnRegCliente = new javax.swing.JButton();
        checkBoxDni = new javax.swing.JCheckBox();
        dialogDetallesCliente = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelDetallesCliente = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtDetallesNombre = new javax.swing.JTextField();
        txtDetallesApellidos = new javax.swing.JTextField();
        txtDetallesEmilio = new javax.swing.JTextField();
        txtDetallesTfno = new javax.swing.JTextField();
        txtDetallesDireccion = new javax.swing.JTextField();
        txtDetallesCiudad = new javax.swing.JTextField();
        txtDetallesCodPostal = new javax.swing.JTextField();
        txtDetallesAlta = new javax.swing.JTextField();
        txtDetallesDNI = new javax.swing.JTextField();
        txtDetallesTipoCliente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDetalles = new javax.swing.JTextArea();
        btnActualizar = new javax.swing.JButton();
        checkBoxDetalles = new javax.swing.JCheckBox();
        cmbDetallesProvincia = new javax.swing.JComboBox<>();
        cmbDetallesEstado = new javax.swing.JComboBox<>();
        panelHistorialCompras = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaDetallesHistorialCompras = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        dialogInactivos = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_inactivos = new javax.swing.JTable();
        btnActivarCliente = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListaClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        efeCinco = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnInactivos = new javax.swing.JButton();

        dialogRegCliente.setBackground(new java.awt.Color(255, 51, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setText("Nuevo cliente");

        txtDNI.setText("jTextField1");

        txtNombre.setText("jTextField1");

        txtApellido.setText("jTextField1");

        txtMail.setText("jTextField1");

        txtTfno.setText("jTextField1");

        txtDireccion.setText("jTextField1");

        txtCiudad.setText("jTextField1");

        cmbProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("DNI");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Apellido(s)");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("e-mail");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Telefono");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Direccion");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Ciudad");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Provincia");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("C.P.");

        txtPostal.setText("jTextField1");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Tipo de cliente");

        cmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Estado");

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEstado.setPreferredSize(new java.awt.Dimension(54, 24));

        txtAreaNotas.setColumns(20);
        txtAreaNotas.setRows(5);
        jScrollPane2.setViewportView(txtAreaNotas);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Notas");

        btnRegCliente.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnRegCliente.setText("Registrar");
        btnRegCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogRegClienteLayout = new javax.swing.GroupLayout(dialogRegCliente.getContentPane());
        dialogRegCliente.getContentPane().setLayout(dialogRegClienteLayout);
        dialogRegClienteLayout.setHorizontalGroup(
            dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTfno, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                    .addComponent(cmbProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkBoxDni)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(txtPostal))
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(btnRegCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        dialogRegClienteLayout.setVerticalGroup(
            dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogRegClienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(checkBoxDni))
                .addGap(18, 18, 18)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(dialogRegClienteLayout.createSequentialGroup()
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTfno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(25, 25, 25)
                        .addGroup(dialogRegClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(jScrollPane2))
                .addGap(48, 48, 48)
                .addComponent(btnRegCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        dialogDetallesCliente.setBackground(new java.awt.Color(255, 102, 0));

        panelDetallesCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Detalles");
        panelDetallesCliente.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 231, 67));

        txtDetallesNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesNombre.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 135, 196, -1));

        txtDetallesApellidos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesApellidos.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 172, 196, -1));

        txtDetallesEmilio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesEmilio.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesEmilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 209, 196, -1));

        txtDetallesTfno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesTfno.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesTfno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 246, 196, -1));

        txtDetallesDireccion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesDireccion.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 135, 196, -1));

        txtDetallesCiudad.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesCiudad.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 196, -1));

        txtDetallesCodPostal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesCodPostal.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesCodPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 172, 196, -1));

        txtDetallesAlta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesAlta.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 209, 196, -1));

        txtDetallesDNI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesDNI.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 290, 196, -1));

        txtDetallesTipoCliente.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtDetallesTipoCliente.setText("jTextField1");
        panelDetallesCliente.add(txtDetallesTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 246, 196, -1));

        txtAreaDetalles.setColumns(20);
        txtAreaDetalles.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAreaDetalles.setRows(5);
        jScrollPane3.setViewportView(txtAreaDetalles);

        panelDetallesCliente.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 135, 207, 218));

        btnActualizar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        panelDetallesCliente.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 386, 294, -1));

        checkBoxDetalles.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        checkBoxDetalles.setText("Editar");
        checkBoxDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDetallesActionPerformed(evt);
            }
        });
        panelDetallesCliente.add(checkBoxDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(629, 26, -1, -1));

        cmbDetallesProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelDetallesCliente.add(cmbDetallesProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 333, 196, -1));

        cmbDetallesEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelDetallesCliente.add(cmbDetallesEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 333, 196, -1));

        jTabbedPane1.addTab("DatosPersonales", panelDetallesCliente);

        panelHistorialCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaDetallesHistorialCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaDetallesHistorialCompras);

        panelHistorialCompras.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 330));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Historial");
        panelHistorialCompras.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, 40));

        jTabbedPane1.addTab("Historial de compras", panelHistorialCompras);

        javax.swing.GroupLayout dialogDetallesClienteLayout = new javax.swing.GroupLayout(dialogDetallesCliente.getContentPane());
        dialogDetallesCliente.getContentPane().setLayout(dialogDetallesClienteLayout);
        dialogDetallesClienteLayout.setHorizontalGroup(
            dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogDetallesClienteLayout.setVerticalGroup(
            dialogDetallesClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetallesClienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        dialogInactivos.setBackground(new java.awt.Color(255, 51, 0));

        tabla_inactivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tabla_inactivos);

        btnActivarCliente.setText("Activar");
        btnActivarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarClienteActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel17.setText("Inactivos");

        javax.swing.GroupLayout dialogInactivosLayout = new javax.swing.GroupLayout(dialogInactivos.getContentPane());
        dialogInactivos.getContentPane().setLayout(dialogInactivosLayout);
        dialogInactivosLayout.setHorizontalGroup(
            dialogInactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogInactivosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogInactivosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 308, Short.MAX_VALUE)
                .addComponent(btnActivarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        dialogInactivosLayout.setVerticalGroup(
            dialogInactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dialogInactivosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(dialogInactivosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActivarCliente))
                .addGap(53, 53, 53)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setOpaque(false);

        tablaListaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaListaClientes);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista de Clientes");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/person_search_50dp_FFFFFF_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        jLabel18.setText("jLabel18");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Acciones disponibles", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        efeCinco.setText("Refrescar");
        efeCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efeCincoActionPerformed(evt);
            }
        });
        jPanel1.add(efeCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, -1));

        btnNuevoCliente.setText("Nuevo cliente");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, -1));

        btnInactivos.setText("Ver inactivos");
        btnInactivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInactivosActionPerformed(evt);
            }
        });
        jPanel1.add(btnInactivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 868, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    


// efeCinco: botón para refrescar la lista de clientes
    private void efeCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efeCincoActionPerformed
       cargarClientes();
    }//GEN-LAST:event_efeCincoActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        dialogRegCliente.setSize(815, 630);
        dialogRegCliente.setLocationRelativeTo(this);
        dialogRegCliente.setVisible(true);
        limpiar_campos_registro();
        cargar_estados();
        cargar_provincias();
        
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnRegClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegClienteActionPerformed
        Cliente cl = new Cliente();
        
        //Validaciones (falta: estado, Provincia)
        if(!evaluar_dni(txtDNI.getText())){
            return;
        }
        if(!evaluar_mail(txtMail.getText().trim().toLowerCase())){
            return;
        }
        if(!validar_telefono(txtTfno.getText().trim())){
            return;
        }
        if(!validar_estado(cmbEstado.getSelectedItem().toString())){
            return;
        }
        if(!evaluar_campos_vacios()){
            return;
        }
        
        
        //Crear Objeto
        cl.setDniCliente(txtDNI.getText().trim().toUpperCase());
        cl.setNombreCl(txtNombre.getText().trim());
        cl.setApellidoCl(txtApellido.getText().trim());        
        cl.setEmailCl(txtMail.getText().trim().toLowerCase());               
        cl.setTelefonoCl(txtTfno.getText().trim());
        cl.setDireccionCl(txtDireccion.getText().trim());
        cl.setCiudad(txtCiudad.getText().trim());
        cl.setCodigoPostal(txtPostal.getText().trim());
        cl.setFechaAlta(new Date());
        cl.setCreatedAt(new Date());
        cl.setNotas(txtAreaNotas.getText());
        cl.setEstado(cmbEstado.getSelectedItem().toString());
        cl.setProvincia(cmbProvincia.getSelectedItem().toString());
        
        //Guardar objeto
        BBDD bd = new BBDD();
        boolean exito = bd.registrar_cliente(cl);
        evaluar_insercion(exito);
    }//GEN-LAST:event_btnRegClienteActionPerformed

    private void checkBoxDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDetallesActionPerformed
        permitir_edicion(checkBoxDetalles.isSelected());
    }//GEN-LAST:event_checkBoxDetallesActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        //Crear objeto cliente y llamar a metodo de guardado
        Cliente c = new Cliente();
        String dni = txtDetallesDNI.getText().trim(); //update WHERE DNI == dni;
        
        boolean comprobar = comprobar_dni_antes_actualizar();
        if(!comprobar){
            return;
        }else{
            BBDD bd = new BBDD();
            c = bd.obtener_cliente_por_dni(dni);
            
            //setear nuevas caracteristicas
            c.setNombreCl(txtDetallesNombre.getText().trim());
            c.setApellidoCl(txtDetallesApellidos.getText().trim());
            c.setEmailCl(txtDetallesEmilio.getText().trim());
            c.setCiudad(txtDetallesCiudad.getText().trim());
            c.setCodigoPostal(txtDetallesCodPostal.getText().trim());
            c.setTelefonoCl(txtDetallesTfno.getText().trim());
            c.setDireccionCl(txtDetallesDireccion.getText().trim());           
            c.setNotas(txtAreaDetalles.getText());
            
            String valorEstado = cmbDetallesEstado.getSelectedItem().toString().trim().toLowerCase();
            
            if (valorEstado.contains("item") || valorEstado.isEmpty()) {
                c.setEstado("activo");
            } else {
                c.setEstado(valorEstado);
            }
            
            boolean exito = bd.actualizar_cliente(c);
            if(exito){
                JOptionPane.showMessageDialog(dialogDetallesCliente, "¡Cliente actualizado correctamente!");
                dialogDetallesCliente.dispose();
                efeCincoActionPerformed(null);
            }else{
                JOptionPane.showMessageDialog(dialogDetallesCliente, "Error al actualizar en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila_eliminar = tablaListaClientes.getSelectedRow();
        boolean exito_eliminar = false;
        BBDD bd = new BBDD();
        
        if(fila_eliminar != -1){
            String dni_eliminar = tablaListaClientes.getValueAt(fila_eliminar, 0).toString();
            int opcion = JOptionPane.showConfirmDialog(this, "¿Desea eliminar esta entrada?", "Aviso", JOptionPane.YES_NO_CANCEL_OPTION);
            switch(opcion){
                case 0:
                    exito_eliminar = bd.eliminar_cliente(dni_eliminar);
                    evaluar_exito(exito_eliminar);
                    break;
                case 1:
                    no_elimina_cliente();
                    break;
                case 2:
                    cancelar_eliminar_cliente();
                    break;
            }
        }else{
            return;
        }
        efeCincoActionPerformed(evt);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnInactivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInactivosActionPerformed
        dialogInactivos.setSize(815, 630);
        dialogInactivos.setLocationRelativeTo(this);
        dialogInactivos.setVisible(true);
        BBDD bd = new BBDD();
        List<Cliente> lista_inactivos = bd.listar_clientes_inactivos();
        llenar_tabla_inactivos(lista_inactivos);
                
    }//GEN-LAST:event_btnInactivosActionPerformed

    private void btnActivarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarClienteActionPerformed
      int numero_fila = tabla_inactivos.getSelectedRow();
      if(numero_fila != -1){
        String dni = tabla_inactivos.getValueAt(numero_fila, 0).toString();      
        BBDD bd = new BBDD();
        boolean exito = bd.activar_cliente(dni);
        if(exito){
            JOptionPane.showMessageDialog(this, "Activado correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Error en la avtivacion", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
          efeCincoActionPerformed(evt);
      }else{
          JOptionPane.showMessageDialog(dialogInactivos, "Por favor, seleccione un cliente inactivo para reactivarlo.", "Aviso", JOptionPane.WARNING_MESSAGE);
      }
      
    }//GEN-LAST:event_btnActivarClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarCliente;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInactivos;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnRegCliente;
    private javax.swing.JCheckBox checkBoxDetalles;
    private javax.swing.JCheckBox checkBoxDni;
    private javax.swing.JComboBox<String> cmbDetallesEstado;
    private javax.swing.JComboBox<String> cmbDetallesProvincia;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JComboBox<String> cmbTipoCliente;
    private javax.swing.JDialog dialogDetallesCliente;
    private javax.swing.JDialog dialogInactivos;
    private javax.swing.JDialog dialogRegCliente;
    private javax.swing.JButton efeCinco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelDetallesCliente;
    private javax.swing.JPanel panelHistorialCompras;
    private javax.swing.JTable tablaDetallesHistorialCompras;
    private javax.swing.JTable tablaListaClientes;
    private javax.swing.JTable tabla_inactivos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextArea txtAreaDetalles;
    private javax.swing.JTextArea txtAreaNotas;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDetallesAlta;
    private javax.swing.JTextField txtDetallesApellidos;
    private javax.swing.JTextField txtDetallesCiudad;
    private javax.swing.JTextField txtDetallesCodPostal;
    private javax.swing.JTextField txtDetallesDNI;
    private javax.swing.JTextField txtDetallesDireccion;
    private javax.swing.JTextField txtDetallesEmilio;
    private javax.swing.JTextField txtDetallesNombre;
    private javax.swing.JTextField txtDetallesTfno;
    private javax.swing.JTextField txtDetallesTipoCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPostal;
    private javax.swing.JTextField txtTfno;
    // End of variables declaration//GEN-END:variables

    public void cargarClientes() {
        BBDD bd = new BBDD();
        List<Cliente> lista_de_clientes = bd.listar_clientes();
        
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("e-Mail");
        modelo.addColumn("Alta");
        modelo.addColumn("Estado");
        
        if (lista_de_clientes != null) {
        for (Cliente c : lista_de_clientes) {
            Object[] fila = new Object[6];
            fila[0] = c.getDniCliente();
            fila[1] = c.getNombreCl();
            fila[2] = c.getApellidoCl();
            fila[3] = c.getEmailCl();
            Date alta = c.getFechaAlta();            
            fila[4] = transform(alta);
            fila[5] = c.getEstado();
            modelo.addRow(fila);
            }
        }
        tablaListaClientes.setModel(modelo);
    }

    private void agregar_listener() {
        tablaListaClientes.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int fila = tablaListaClientes.getSelectedRow();
                    if (fila != -1) {
                        String dni = tablaListaClientes.getValueAt(fila, 0).toString();
                        
                        BBDD bd = new BBDD();
                        Cliente c = bd.obtener_cliente_por_dni(dni);
                        
                        if(c != null){
                            txtDetallesDNI.setText(c.getDniCliente());
                            txtDetallesNombre.setText(c.getNombreCl());
                            txtDetallesApellidos.setText(c.getApellidoCl());
                            txtDetallesEmilio.setText(c.getEmailCl());
                            txtDetallesDireccion.setText(c.getDireccionCl());
                            txtDetallesTfno.setText(c.getTelefonoCl());
                            txtDetallesCodPostal.setText(c.getCodigoPostal());
                            txtDetallesTipoCliente.setText(c.getTipoCliente());
                            if(c.getFechaAlta() != null){
                                txtDetallesAlta.setText(transform(c.getFechaAlta()));
                            }
                            txtAreaDetalles.setText(c.getNotas());
                            
                            cargar_historial_compras(dni);
                            
                            checkBoxDetalles.setSelected(false);
                            permitir_edicion(false);
                            
                            dialogDetallesCliente.pack();
                            dialogDetallesCliente.setSize(743, 610);
                            dialogDetallesCliente.setLocationRelativeTo(null);
                            dialogDetallesCliente.setVisible(true);                            
                        }
                    }
                }
            }
        });        
    }
    
    private void limpiar_campos_registro(){
        txtDNI.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCiudad.setText("");
        txtDireccion.setText("");
        txtMail.setText("");
        txtPostal.setText("");
        txtTfno.setText("");
    }
    
    private void cargar_estados(){
        cmbEstado.removeAllItems();
        for (String estado : estados)
        {
            cmbEstado.addItem(estado);
        }
    }

    private void evaluar_insercion(boolean exito) {
        if(!exito){
            JOptionPane.showMessageDialog(btnRegCliente, "No se pudo registrar el cliente\nVerifique correcta inserción de datos", "Aviso", JOptionPane.ERROR_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(btnRegCliente, "Cliente registrado", "Confirmación", JOptionPane.WARNING_MESSAGE);
        }
    }

    private boolean evaluar_dni(String este_dni) {
        Boolean correcto = false;
        String dni = este_dni.trim().toUpperCase();
        if(!dni.matches(".*[A-Z]$")){
            JOptionPane.showMessageDialog(this, "Introduzca DNI válido", "Aviso", JOptionPane.ERROR_MESSAGE);
            txtDNI.setText("");
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private boolean evaluar_mail(String emilio) {
        Boolean correcto = false;
        if(!emilio.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")){
            JOptionPane.showMessageDialog(this, "Introduzca email válido", "Aviso", JOptionPane.ERROR_MESSAGE);
            txtMail.setText("");
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private boolean validar_telefono(String tfno) {
        Boolean correcto = false;
        if(!tfno.matches("^[0-9]{9}$")){
            JOptionPane.showMessageDialog(this, "Introduzca telefono válido", "Aviso", JOptionPane.ERROR_MESSAGE);
            txtTfno.setText("");
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private void cargar_provincias() {
        cmbProvincia.removeAllItems();
        BBDD bd = new BBDD();
        List<Provincia> listado_provincias = bd.listar_provincias();
        for (Provincia listado : listado_provincias)
        {
            cmbProvincia.addItem(listado.getNombreProvincia());
        }
    }

    private boolean validar_estado(String estado) {
        Boolean correcto = false;        
        if(!estado.matches("activo")){
            JOptionPane.showConfirmDialog(this, "El cliente no está configurado activo", "Aviso", JOptionPane.OK_OPTION);
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private boolean evaluar_campos_vacios() {
        Boolean correcto = false;
        if(txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() || txtCiudad.getText().isEmpty() || txtDireccion.getText().isEmpty() || txtTfno.getText().isEmpty()){
            correcto = false;
        }else{
            correcto = true;
        }
        return correcto;
    }

    private String transform(Date alta) {
        if (alta == null) {
            return ""; 
        }       
        SimpleDateFormat formateador = new SimpleDateFormat("dd-MM-yyyy");       
        return formateador.format(alta);
    }
    
    private void permitir_edicion(boolean activar){
        txtDetallesDNI.setEditable(false);
        txtDetallesAlta.setEditable(false);
        
        txtDetallesNombre.setEditable(activar);
        txtDetallesApellidos.setEditable(activar);
        txtDetallesEmilio.setEditable(activar);
        txtDetallesDireccion.setEditable(activar);
        txtDetallesCodPostal.setEditable(activar);
        txtDetallesTfno.setEditable(activar);
        txtDetallesCiudad.setEditable(activar);        
        txtDetallesTipoCliente.setEditable(activar);
        cmbDetallesProvincia.setEditable(activar);
        cmbDetallesEstado.setEditable(activar);
        btnActualizar.setEnabled(activar);
    }    
    
    private boolean comprobar_dni_antes_actualizar(){
        if (txtDetallesDNI.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El DNI no puede estar vacío", "Error", JOptionPane.ERROR_MESSAGE);        
        }
        return true;
    }
    
    private void asignar_estados(){        
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(estados));
        cmbDetallesEstado.setModel(new javax.swing.DefaultComboBoxModel<>(estados));
    }
    
    private void cargar_historial_compras(String dniCliente) {
        try {
            BBDD bd = new BBDD();            
            List<Venta> lista_compras = bd.obtener_compras_por_cliente(dniCliente); 

            llenar_tabla_historial(lista_compras);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar el historial: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }        
    }

    private void cancelar_eliminar_cliente() {
        JOptionPane.showConfirmDialog(this, "Se canceló la operacion", "Aviso", JOptionPane.WARNING_MESSAGE);
    }

    private void no_elimina_cliente() {
        JOptionPane.showConfirmDialog(this, "Se canceló la operacion", "Aviso", JOptionPane.WARNING_MESSAGE);
    }

    private void evaluar_exito(boolean exito_eliminar) {
        if(exito_eliminar){
            JOptionPane.showMessageDialog(this, "Se eliminó correctamente", "Notificacion", JOptionPane.OK_OPTION);
        }else{
            JOptionPane.showMessageDialog(this, "Problema al eliminar.\nError", "Notificacion", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void configurar_tabla_historial(){
        String[] columnas = {"ID Venta", "Fecha", "Total", "Metodo Pago"};
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tablaDetallesHistorialCompras.setModel(modelo);
    }

    private void llenar_tabla_historial(List<Venta> lista_compras) {
        DefaultTableModel modelo = (DefaultTableModel) tablaDetallesHistorialCompras.getModel();
        modelo.setRowCount(0);
        if (lista_compras != null && !lista_compras.isEmpty()) {
            for (Venta venta : lista_compras) {               
                Object[] fila = {
                    venta.getIdVenta() != null ? venta.getIdVenta() : "N/A", 
                    venta.getFechaVenta() != null ? transform(venta.getFechaVenta()) : "Sin fecha", 
                    venta.getTotal() != null ? String.format("%.2f €", venta.getTotal().doubleValue()) : "0.00 €",
                    venta.getMetodoPago() != null ? venta.getMetodoPago() : "No especificado"
                };
                modelo.addRow(fila);
            }
        }
    }

    private void configurar_tabla_inactivos(){
        String[] columnas = {"DNI", "Nombre", "Apellidos", "Email", "Teléfono"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Evitamos que el usuario edite las celdas directamente
        }
    };
    tabla_inactivos.setModel(modelo);
    }
    
    private void llenar_tabla_inactivos(List<Cliente> lista_inactivos) {
    DefaultTableModel modelo = (DefaultTableModel) tabla_inactivos.getModel();
    modelo.setRowCount(0);
    
    if (lista_inactivos != null && !lista_inactivos.isEmpty()) {
        for (Cliente cliente : lista_inactivos) {
            Object[] fila = {
                cliente.getDniCliente(),
                cliente.getNombreCl(),
                cliente.getApellidoCl(),
                cliente.getEmailCl(),
                cliente.getTelefonoCl()
            };
            modelo.addRow(fila);
        }
    }
}
}

