/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.Color;
import java.util.List;
import modelo.BBDD;
import vista_componentes_graficas.CurveLineChart;
import vista_componentes_graficas.ModelChart;

/**
 *
 * @author Usuario
 */
public class VentanaGraficas extends javax.swing.JPanel {
    private CurveLineChart chartAnimado;
    private final BBDD bd = new BBDD();
    /**
     * Creates new form VentanaGraficas
     */
    public VentanaGraficas() {
        initComponents();
        inicializar_y_estilizar_grafica();
        cargar_datos_almacen();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelGraficas_1 = new javax.swing.JPanel();
        panelGraficas_2 = new javax.swing.JPanel();

        setOpaque(false);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Graficas");

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/analytics_50dp_000000_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N

        panelGraficas_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPane1.addTab("tab1", panelGraficas_1);

        javax.swing.GroupLayout panelGraficas_2Layout = new javax.swing.GroupLayout(panelGraficas_2);
        panelGraficas_2.setLayout(panelGraficas_2Layout);
        panelGraficas_2Layout.setHorizontalGroup(
            panelGraficas_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1002, Short.MAX_VALUE)
        );
        panelGraficas_2Layout.setVerticalGroup(
            panelGraficas_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", panelGraficas_2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelGraficas_1;
    private javax.swing.JPanel panelGraficas_2;
    // End of variables declaration//GEN-END:variables
    
    private void inicializar_y_estilizar_grafica() {    
    chartAnimado = new CurveLineChart();    
    chartAnimado.setBackground(new java.awt.Color(10, 17, 31));
    
    
    chartAnimado.setTitle("Ocupación de Stock por Pasillos");
    chartAnimado.addLegend("Capacidad Actual", new Color(12, 194, 240));
    chartAnimado.addLegend("Límite de Alerta", new Color(238, 7, 137));
    
    
    panelGraficas_1.setLayout(new java.awt.BorderLayout());
    panelGraficas_1.add(chartAnimado, java.awt.BorderLayout.CENTER);
    panelGraficas_1.validate();
    }
    
    private void cargar_datos_simulados() {
        chartAnimado.clear();
        
        
        chartAnimado.addData(new ModelChart("Pasillo A", new double[]{45, 80}));
        chartAnimado.addData(new ModelChart("Pasillo B", new double[]{75, 80}));
        chartAnimado.addData(new ModelChart("Pasillo C", new double[]{20, 80}));
        chartAnimado.addData(new ModelChart("Pasillo D", new double[]{95, 80})); 
        chartAnimado.addData(new ModelChart("Pasillo E", new double[]{60, 80}));
        
        
        chartAnimado.start();
    }

    private void cargar_datos_almacen() {
        chartAnimado.clear();
        
        List<Object[]> registros = bd.obtener_stock_por_pasillo();
        
        if (registros != null && !registros.isEmpty()) {
            for (Object[] fila : registros) {
                String labelPasillo = "Pasillo " + String.valueOf(fila[0]);
                long cantidad = (Long) fila[1];                 
                chartAnimado.addData(new ModelChart(labelPasillo, new double[]{cantidad, 4.0}));
            }
        } else {
            chartAnimado.addData(new ModelChart("Sin Datos", new double[]{0, 15.0}));
        }
        chartAnimado.start(); 
    }
}


