/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Font;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import modelo.BBDD;
import pojos_package.*;
import pojos_package.Inventario;
import pojos_package.Proveedor;
import pojos_package.Ubicacion;

/**
 *
 * @author Usuario
 */
public class VentanaRegistro extends javax.swing.JPanel {
    
    List<Proveedor> proveedores;
    List<String> articulos;
    List<String> estados;

    /**
     * Creates new form VentanaRegistro
     */
    public VentanaRegistro() {
        initComponents();
        fijar_tamaño_panel_fecha();
        cargar_componentes_cmbox_tipoart();
        cargar_componentes_cmbox_estante();
        cargar_componentes_cmbox_pasillo();
        cargar_componentes_cmbox_estado();
        cargar_componentes_cmbox_proveedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        label1 = new java.awt.Label();
        txtNuevoArticulo = new java.awt.TextField();
        btn_nuevoart_aceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmb_nuevoart_proveedor = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbox_tipo_articulo = new javax.swing.JComboBox<>();
        btn_regnuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        reg_numserie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        cmbox_reg_pasillo = new javax.swing.JComboBox<>();
        cmbox_reg_estante = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbox_estado = new javax.swing.JComboBox<>();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        jLabel8 = new javax.swing.JLabel();
        cmbProveedor = new javax.swing.JComboBox<>();

        jDialog1.setBackground(new java.awt.Color(255, 255, 255));
        jDialog1.setMinimumSize(new java.awt.Dimension(300, 200));

        label1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label1.setText("Nuevo articulo");

        btn_nuevoart_aceptar.setBackground(new java.awt.Color(255, 255, 255));
        btn_nuevoart_aceptar.setForeground(new java.awt.Color(0, 0, 0));
        btn_nuevoart_aceptar.setText("Aceptar");
        btn_nuevoart_aceptar.setBorder(null);
        btn_nuevoart_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoart_aceptarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cancelar");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cmb_nuevoart_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btn_nuevoart_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNuevoArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(cmb_nuevoart_proveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(cmb_nuevoart_proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(txtNuevoArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevoart_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        setOpaque(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Articulo: ");

        cmbox_tipo_articulo.setBackground(new java.awt.Color(255, 255, 255));
        cmbox_tipo_articulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbox_tipo_articulo.setForeground(new java.awt.Color(0, 0, 0));
        cmbox_tipo_articulo.setOpaque(false);
        cmbox_tipo_articulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbox_tipo_articuloActionPerformed(evt);
            }
        });

        btn_regnuevo.setBackground(new java.awt.Color(255, 255, 255));
        btn_regnuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_regnuevo.setForeground(new java.awt.Color(0, 0, 0));
        btn_regnuevo.setText("+ Crear nuevo");
        btn_regnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regnuevoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Proveedor: ");

        reg_numserie.setBackground(new java.awt.Color(255, 255, 255));
        reg_numserie.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        reg_numserie.setForeground(new java.awt.Color(0, 0, 0));
        reg_numserie.setText("introduzca numero de serie...");
        reg_numserie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                reg_numserieFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                reg_numserieFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Pasillo :");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estado: ");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Registrar Stock");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/database_upload_50dp_000000_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N

        btn_registrar.setBackground(new java.awt.Color(255, 255, 255));
        btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/check_50dp_000000_FILL0_wght400_GRAD0_opsz48.png"))); // NOI18N
        btn_registrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), null, null));
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });

        cmbox_reg_pasillo.setBackground(new java.awt.Color(255, 255, 255));
        cmbox_reg_pasillo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbox_reg_pasillo.setForeground(new java.awt.Color(0, 0, 0));
        cmbox_reg_pasillo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione pasillo..." }));

        cmbox_reg_estante.setBackground(new java.awt.Color(255, 255, 255));
        cmbox_reg_estante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbox_reg_estante.setForeground(new java.awt.Color(0, 0, 0));
        cmbox_reg_estante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione estante..." }));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Estante: ");

        cmbox_estado.setBackground(new java.awt.Color(255, 255, 255));
        cmbox_estado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbox_estado.setForeground(new java.awt.Color(0, 0, 0));

        dateChooserPanel1.setCalendarBackground(new java.awt.Color(255, 255, 255));
        dateChooserPanel1.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);
        dateChooserPanel1.setShowOneMonth(true);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Numero Serie: ");

        cmbProveedor.setBackground(new java.awt.Color(255, 255, 255));
        cmbProveedor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbProveedor.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reg_numserie, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbox_tipo_articulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbox_reg_pasillo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbox_reg_estante, 0, 215, Short.MAX_VALUE)
                                .addComponent(cmbox_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(51, 74, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateChooserPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_regnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbox_tipo_articulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reg_numserie, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbox_reg_pasillo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbox_reg_estante, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbox_estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(dateChooserPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regnuevoActionPerformed
      cargar_proveedores_jdialog();
      jDialog1.setLocationRelativeTo(this);
      jDialog1.pack();
      jDialog1.setModal(true); 
      jDialog1.setVisible(true);
      
    }//GEN-LAST:event_btn_regnuevoActionPerformed

    private void btn_nuevoart_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoart_aceptarActionPerformed
        String nombre_articulo = txtNuevoArticulo.getText().trim();

        if (nombre_articulo.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "El nombre del artículo no puede estar vacío.");
            return;
        }

        String item = cmb_nuevoart_proveedor.getSelectedItem().toString();

        if (item.equals("Seleccione proveedor...")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes seleccionar un proveedor.");
            return;
        }

        Proveedor proveedor = null;

        for (Proveedor p : proveedores) {
            if (p.getNombreProov().equals(item)) {
                proveedor = p;
                break;
            }
        }

        if (proveedor == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Proveedor no encontrado.");
            return;
        }

        // =========================
        // ERP N:M REAL
        // =========================
        Articulo art = new Articulo();
        art.setNombreArt(nombre_articulo);

        ArticuloProveedor ap = new ArticuloProveedor();
        ap.setArticulo(art);
        ap.setProveedor(proveedor);

        java.util.Set<ArticuloProveedor> set = new java.util.HashSet<>();
        set.add(ap);

        art.setArticuloProveedors(set);

        BBDD bd = new BBDD();

        boolean ok = bd.insertar_articulo(art);

        if (ok) {
            javax.swing.JOptionPane.showMessageDialog(this, "Artículo creado correctamente.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar artículo.");
        }

        cargar_componentes_cmbox_tipoart();
    }//GEN-LAST:event_btn_nuevoart_aceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jDialog1.dispose(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        Integer pasillo = obtener_pasillo();
        Integer estante = obtener_estante();
        String numero_serie = obtener_numserie();
        Calendar calendario = dateChooserPanel1.getSelectedDate();
        Date fecha_registro = calendario.getTime();
        String estado_string = cmbox_estado.getSelectedItem().toString();
        Estado_inventario estado = Estado_inventario.valueOf(estado_string);
        Proveedor prov = (Proveedor) cmbProveedor.getSelectedItem();        

        if (pasillo == null || estante == null || numero_serie == null) return;

        BBDD bd = new BBDD();
        Ubicacion ubi = new Ubicacion(pasillo, estante);
        ubi = bd.insertar_ubicacion(ubi);

        String nombre_articulo = cmbox_tipo_articulo.getSelectedItem().toString();

        Articulo articulo = bd.obtener_articulo_por_nombre(nombre_articulo);

        if (articulo == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Artículo no encontrado.");
            return;
        }
        
        Inventario inv = new Inventario(numero_serie, articulo, ubi, estado, fecha_registro, prov);

        boolean ok = bd.registrar_en_inventario(inv);
        if (ok) {
            javax.swing.JOptionPane.showMessageDialog(this, "Inventario registrado correctamente.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al registrar inventario.");
        }       
    }//GEN-LAST:event_btn_registrarActionPerformed
 
    
    
    private void cmbox_tipo_articuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbox_tipo_articuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbox_tipo_articuloActionPerformed

    private void reg_numserieFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_numserieFocusGained
        reg_numserie.setText("");
    }//GEN-LAST:event_reg_numserieFocusGained

    private void reg_numserieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_reg_numserieFocusLost
       if(!reg_numserie.getText().isEmpty())
           return;
       else{
         reg_numserie.setText("Introduzca numero de serie...");  
       }       
    }//GEN-LAST:event_reg_numserieFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nuevoart_aceptar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_regnuevo;
    private javax.swing.JComboBox<Proveedor> cmbProveedor;
    private javax.swing.JComboBox<String> cmb_nuevoart_proveedor;
    private javax.swing.JComboBox<Estado_inventario> cmbox_estado;
    private javax.swing.JComboBox<Object> cmbox_reg_estante;
    private javax.swing.JComboBox<Object> cmbox_reg_pasillo;
    private javax.swing.JComboBox<Articulo> cmbox_tipo_articulo;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private javax.swing.JTextField reg_numserie;
    private java.awt.TextField txtNuevoArticulo;
    // End of variables declaration//GEN-END:variables

    public void cargar_componentes_cmbox_tipoart() {
        cmbox_tipo_articulo.removeAllItems();
        //cmbox_tipo_articulo.addItem("Seleccione tipo...");

    try {
        BBDD bd = new BBDD();
        List<Articulo> articulos = bd.listar_articulos();        

        if (articulos != null) {
            for (Articulo art : articulos) {
                if (art != null && !art.getNombreArt().isEmpty()) {
                    cmbox_tipo_articulo.addItem(art);
                }
            }
        }
    } catch (Exception e) {
        System.err.println("Error al cargar artículos: " + e.getMessage());        
        }
    }    
    
    public void cargar_proveedores_jdialog(){
    
       cmb_nuevoart_proveedor.removeAllItems();
       BBDD bd = new BBDD();
       proveedores = bd.obtener_proveedores();       
       
       if(proveedores != null){
           cmb_nuevoart_proveedor.addItem("Seleccione proveedor...");
           for (Proveedor proveedor : proveedores)
           {
               cmb_nuevoart_proveedor.addItem(proveedor.getNombreProov());
           }
       }
        
    }  

    public void cargar_componentes_cmbox_estante() {
        cmbox_reg_estante.removeAllItems();
        cmbox_reg_estante.addItem("Seleccione estante");
        for (int i = 1; i <= 3; i++)
        {
            cmbox_reg_estante.addItem(i);
        }
    }

    public void cargar_componentes_cmbox_pasillo() {
        cmbox_reg_pasillo.removeAllItems();
        cmbox_reg_pasillo.addItem("Seleccione pasillo...");
        for (int i = 1; i <= 10; i++)
        {
            cmbox_reg_pasillo.addItem(i);
        }
    }
    
    public void cargar_componentes_cmbox_estado(){
        cmbox_estado.removeAllItems();        
        for (Estado_inventario estado : Estado_inventario.values())
        {
            cmbox_estado.addItem(estado);
        }        
    }
    
    private Integer obtener_pasillo(){
        Object item_pasillo = cmbox_reg_pasillo.getSelectedItem();
        if (item_pasillo == null || item_pasillo instanceof String) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un valor válido.", 
            "Error de Selección", javax.swing.JOptionPane.ERROR_MESSAGE);        
        return null; 
        }
        return (Integer) item_pasillo;
    }
    
    private Integer obtener_estante(){
        Object item_estante = cmbox_reg_estante.getSelectedItem();
        if(item_estante == null || item_estante instanceof String){
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un valor válido.", 
            "Error de Selección", javax.swing.JOptionPane.ERROR_MESSAGE);        
            return null;
        }
        return (Integer) item_estante;
    }
    
    private String obtener_numserie() {
    String num_serie_string = reg_numserie.getText().trim();    
    if (num_serie_string.isEmpty() || num_serie_string.equals("introduzca numero de serie...")) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "El Número de Serie no puede estar vacío.", "Error de Entrada", javax.swing.JOptionPane.ERROR_MESSAGE
        );
        return null;
    }
    return num_serie_string;
}

    private void fijar_tamaño_panel_fecha() {
        dateChooserPanel1.setPreferredSize(new java.awt.Dimension(400, 300));
        dateChooserPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
    }

    private void cargar_componentes_cmbox_proveedor() {
        BBDD bd = new BBDD();
        List<Proveedor> lista_proveedores = bd.listar_proveedores();
        for (Proveedor proveedor : lista_proveedores)
        {
            cmbProveedor.addItem(proveedor);
        }
    }

    
    
}

//TAREAS
//encapsular metodos
//terminar insercion
//-> obtener ojetos articulo a partir del nombre_art




